
baseURL = "https://gerrieosimowicz.com/"
languageCode = "en-us"
title = 'In memoriam Geraldine "Gerrie" Osimowicz'
theme = "notrack"
newContentEditor = "nvim"
#mainSections = ["blog"]
# disqusShortname = "example"
paginate = 4

[params]
  author = "Gerrie Osimowicz"
  siteHeading = 'In memoriam of Geraldine "Gerrie" Osimowicz' # defaults to author
  #showBlogLatest = true
  #mainSections = ["blog"]
  showTaxonomyLinks = false
  #nBlogLatest = 0 # number of blog post om the home page
  #blogLatestHeading = "My writing"


[taxonomies]
  year = "year"
  month = "month"
  tags = "tags"
  categories = "categories"

#[permalinks]
 #blog = "/blog/:year/:month/:slug"